export const SENSOR_DATA_RECEIVED = 'SENSOR_DATA_RECEIVED';
export const SENSOR_DATA_CHECK = 'SENSOR_DATA_CHECK';
export const DELETE_SENSOR_DATA = 'DELETE_SENSOR_DATA';
export const UPDATE_HOSPITAL_BEDS = 'UPDATE_HOSPITAL_BEDS';
