export const SENSOR_DATA_RECEIVED = 'SENSOR_DATA_RECEIVED';
export const SENSOR_DATA_CHECK = 'SENSOR_DATA_CHECK';
export const DELETE_SENSOR_DATA = 'DELETE_SENSOR_DATA';
export const RESET_HOSPITAL_BEDS = 'RESET_HOSPITAL_BEDS';
export const ADD_HOSPITAL_BED = 'ADD_HOSPITAL_BEDS';
